### ISSUE TITLE
nice job looking good.

### ISSUE THREAD

**Issue by marcus7777** [motss/compound-timepicker#1]
Anything I can do to help?
Maybe I could get the day and night pictures to swap over depending on what time the you were picking?

**Comment by motss** [comment]
@marcus7777 Wow... that would be a great enhancement! Maybe you can submit a PR on that?
The only problem I'm facing is the pictures will not show as `vulcanize` won't able to recognize them when this element is being vulcanized. I'm thinking of serving the pictures from a server.

**Comment by marcus7777** [comment]
@motss 
Or we could simplify (because we don't need the bottom half) them and put them in-line: [ref](http://stackoverflow.com/questions/10768451/inline-svg-in-css)
This would allow the vulcanized code to work I think.
What do you think of that approach?

**Comment by motss** [comment]
@marcus7777 I'll try on that later. Thanks for the idea.

**Comment by motss** [comment]
28f9fd958cab06cb2543f1cf2e84615eef64b7a3 should fix.
